[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
bytes = "1.5.0"
thiserror = "1.0.50"
num-bigint = "0.4.4"
num-integer = "0.1.45"
